/*Missing value analysis*/

SELECT
SUM(CASE WHEN Customer_ID IS NULL THEN 1 ELSE 0 END)AS Customer_ID_Null,
SUM(CASE WHEN Customer_Name IS NULL THEN 1 ELSE 0 END)AS Customer_Name_Null,
SUM(CASE WHEN Gender IS NULL THEN 1 ELSE 0 END)AS Gender_Null,
SUM(CASE WHEN Age IS NULL THEN 1 ELSE 0 END)AS Age_Null,
SUM(CASE WHEN Age_Group IS NULL THEN 1 ELSE 0 END)AS Age_Group_Null,
SUM(CASE WHEN Date_of_Birth IS NULL THEN 1 ELSE 0 END)AS Date_of_Birth_Null,
SUM(CASE WHEN Email IS NULL THEN 1 ELSE 0 END)AS Email_Null,
SUM(CASE WHEN Phone IS NULL THEN 1 ELSE 0 END)AS Phone_Null,
SUM(CASE WHEN City IS NULL THEN 1 ELSE 0 END)AS City_Null,
SUM(CASE WHEN State IS NULL THEN 1 ELSE 0 END)AS State_Null,
SUM(CASE WHEN Pincode IS NULL THEN 1 ELSE 0 END)AS Pincode,
SUM(CASE WHEN Registration_Date IS NULL THEN 1 ELSE 0 END)AS Registration_Date_Null,
SUM(CASE WHEN Customer_Tier IS NULL THEN 1 ELSE 0 END)AS Customer_Tier_Null,
SUM(CASE WHEN Total_Orders IS NULL THEN 1 ELSE 0 END)AS Total_Orders_Null,
SUM(CASE WHEN Total_Spent IS NULL THEN 1 ELSE 0 END)AS Total_Spent_Null
FROM customers;

SELECT
SUM(CASE WHEN Product_ID IS NULL THEN 1 ELSE 0 END) AS Product_ID_NULL,
SUM(CASE WHEN Product_Name IS NULL THEN 1 ELSE 0 END) AS Product_ID_NULL,
SUM(CASE WHEN Category IS NULL THEN 1 ELSE 0 END) AS Product_ID_NULL,
SUM(CASE WHEN Brand IS NULL THEN 1 ELSE 0 END) AS Product_ID_NULL,
SUM(CASE WHEN Original_Price IS NULL THEN 1 ELSE 0 END) AS Product_ID_NULL,
SUM(CASE WHEN Discount_Percent IS NULL THEN 1 ELSE 0 END) AS Product_ID_NULL,
SUM(CASE WHEN Discount_Amount IS NULL THEN 1 ELSE 0 END) AS Product_ID_NULL,
SUM(CASE WHEN Selling_Price IS NULL THEN 1 ELSE 0 END) AS Product_ID_NULL,
SUM(CASE WHEN Stock_Quantity IS NULL THEN 1 ELSE 0 END) AS Product_ID_NULL,
SUM(CASE WHEN Weight_kg IS NULL THEN 1 ELSE 0 END) AS Product_ID_NULL,
SUM(CASE WHEN Avg_Rating IS NULL THEN 1 ELSE 0 END) AS Product_ID_NULL,
SUM(CASE WHEN Total_Reviews IS NULL THEN 1 ELSE 0 END) AS Product_ID_NULL
FROM products;

SELECT
SUM(CASE WHEN Order_ID IS NULL THEN 1 ELSE 0 END) AS Order_ID_NULL,
SUM(CASE WHEN Customer_ID IS NULL THEN 1 ELSE 0 END) AS Customer_ID_NULL,
SUM(CASE WHEN Product_ID IS NULL THEN 1 ELSE 0 END) AS Product_IDProduct_ID_NULL,
SUM(CASE WHEN Order_Date IS NULL THEN 1 ELSE 0 END) AS Order_Date_NULL,
SUM(CASE WHEN Order_Time IS NULL THEN 1 ELSE 0 END) AS Order_Time_NULL,
SUM(CASE WHEN Delivery_Date IS NULL THEN 1 ELSE 0 END) AS Delivery_Date_NULL,
SUM(CASE WHEN Quantity IS NULL THEN 1 ELSE 0 END) AS Quantity_NULL,
SUM(CASE WHEN Unit_Price IS NULL THEN 1 ELSE 0 END) AS Unit_Price_NULL,
SUM(CASE WHEN Order_Value IS NULL THEN 1 ELSE 0 END) AS Order_Value_NULL,
SUM(CASE WHEN Shipping_Cost IS NULL THEN 1 ELSE 0 END) AS Shipping_Cost_NULL,
SUM(CASE WHEN Coupon_Code IS NULL THEN 1 ELSE 0 END) AS Coupon_Code_NULL,
SUM(CASE WHEN Coupon_Discount IS NULL THEN 1 ELSE 0 END) AS Coupon_Discount_NULL,
SUM(CASE WHEN Total_Amount IS NULL THEN 1 ELSE 0 END) AS Total_Amount_NULL,
SUM(CASE WHEN Payment_Mode IS NULL THEN 1 ELSE 0 END) AS Payment_Mode_NULL,
SUM(CASE WHEN Order_Status IS NULL THEN 1 ELSE 0 END) AS Order_Status_NULL,
SUM(CASE WHEN Rating IS NULL THEN 1 ELSE 0 END) AS Rating_NULL,
SUM(CASE WHEN Review_Text IS NULL THEN 1 ELSE 0 END) AS Review_Text_NULL,
SUM(CASE WHEN City IS NULL THEN 1 ELSE 0 END) AS City_NULL,
SUM(CASE WHEN State IS NULL THEN 1 ELSE 0 END) AS State_NULL,
SUM(CASE WHEN Customer_Age IS NULL THEN 1 ELSE 0 END) AS Customer_Age_NULL,
SUM(CASE WHEN Customer_Age_Group IS NULL THEN 1 ELSE 0 END) AS Customer_Age_Group_NULL
FROM sales;

SELECT *
FROM sales
WHERE Coupon_Code IS NULL;

SELECT *
FROM sales
WHERE Rating IS NULL;

SELECT *
FROM sales
WHERE Review_Text IS NULL;


